name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.github/graphics/**'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to use for the deployment (default: latest)'
        type: string
        default: latest

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  deployments: write

jobs:
  builds:
    name: Builds
    uses: ./.github/workflows/.build-images.yml
    permissions:
      packages: write
    with:
      tags: ${{ inputs.tags || 'latest' }}
  
  # Make deploy-test depend on builds
  deploy-test:
    name: Deploy (TEST)
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      bcgov_sso_api_client_id: ${{ secrets.BCGOV_SSO_API_CLIENT_ID }}
      bcgov_sso_api_client_secret: ${{ secrets.BCGOV_SSO_API_CLIENT_SECRET }}
      vite_keycloak_client_id: ${{ secrets.VITE_KEYCLOAK_CLIENT_ID }}
    with:
      release_name: ${{ github.event.repository.name }}-test
      environment: test
      db_user: app
      tag: ${{ inputs.tags || 'latest' }}  # Use the same tag that was built
      params: >-
        --set backend.deploymentStrategy=RollingUpdate
        --set frontend.deploymentStrategy=RollingUpdate
        --set backend.imagePullPolicy=Always
        --set frontend.imagePullPolicy=Always
        --set global.autoscaling=true
        --set frontend.pdb.enabled=true
        --set backend.pdb.enabled=true
      deployment_url: https://${{ github.event.repository.name }}-test-frontend.apps.silver.devops.gov.bc.ca

  test_security_scan:
    permissions:
      contents: read
    name: ZAP Security Scan (TEST)
    needs: [deploy-test]
    uses: ./.github/workflows/.zap-scan.yml
    with:
      target_url: https://${{ github.event.repository.name }}-test-frontend.apps.silver.devops.gov.bc.ca
      fail_on_high: true
      scan_type: full

  # Manual approval step before production deployment
  approve-prod:
    name: Approve Production Deployment
    needs: [builds, test_security_scan]  # Wait for security scan to pass
    runs-on: ubuntu-24.04
    environment:
      name: PROD
    steps:
      - name: Manual Approval Required
        run: |
          echo "Manual approval required for production deployment"
          echo "Test environment: https://${{ github.event.repository.name }}-test-frontend.apps.silver.devops.gov.bc.ca"
          echo "Security scan completed successfully"
          echo "Ready for production deployment"

  deploy-prod:
    name: Deploy (PROD)
    needs: [approve-prod]  # Wait for manual approval
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      bcgov_sso_api_client_id: ${{ secrets.BCGOV_SSO_API_CLIENT_ID }}
      bcgov_sso_api_client_secret: ${{ secrets.BCGOV_SSO_API_CLIENT_SECRET }}
      vite_keycloak_client_id: ${{ secrets.VITE_KEYCLOAK_CLIENT_ID }}
    with:
      release_name: ${{ github.event.repository.name }}-prod
      environment: prod
      db_user: app
      tag: ${{ inputs.tags || 'latest' }}  # Use the same tag that was built
      params: >-
        --set backend.deploymentStrategy=RollingUpdate
        --set frontend.deploymentStrategy=RollingUpdate
        --set backend.imagePullPolicy=Always
        --set frontend.imagePullPolicy=Always
        --set global.autoscaling=true
        --set frontend.pdb.enabled=true
        --set backend.pdb.enabled=true
      deployment_url: https://${{ github.event.repository.name }}-prod-frontend.apps.silver.devops.gov.bc.ca

  # Commented out promote job - causing issues with PR tags
  # promote:
  #   name: Promote Images to Latest
  #   needs: [deploy-prod]
  #   if: ${{ inputs.tags && inputs.tags != 'latest' && !startsWith(inputs.tags, 'pr-') }}
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       package: [migrations, backend, frontend]
  #   timeout-minutes: 1
  #   steps:
  #     - name: Debug promotion info
  #       run: |
  #         echo "Promoting ${{ inputs.tags }} to latest for package ${{ matrix.package }}"
  #         echo "Source tag (target): ${{ inputs.tags }}"
  #         echo "Destination tag (tags): latest"
  #
  #     - name: Promote to latest
  #       uses: shrink/actions-docker-registry-tag@f04afd0559f66b288586792eb150f45136a927fa
  #       with:
  #         registry: ghcr.io
  #         repository: ${{ github.repository }}/${{ matrix.package }}
  #         target: ${{ inputs.tags }}  # Source: the tag we built (e.g., v1.2.3)
  #         tags: latest  # Destination: promote to latest