name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  pull-requests: write
  packages: write  # Added for image operations

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  builds:
    name: Builds
    uses: ./.github/workflows/.build-images.yml
    permissions:
      packages: write
    with:
      tags: pr-${{ github.event.pull_request.number }}
      keep_versions: 5  # Keep fewer versions for PR builds

  # Deploy each PR to its own environment
  deploys:
    name: Deploy PR-${{ github.event.number }} Environment
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      bcgov_sso_api_client_id: ${{ secrets.BCGOV_SSO_API_CLIENT_ID }}
      bcgov_sso_api_client_secret: ${{ secrets.BCGOV_SSO_API_CLIENT_SECRET }}
      vite_keycloak_client_id: ${{ secrets.VITE_KEYCLOAK_CLIENT_ID }}
    with:
      release_name: ${{ github.event.repository.name }}-pr-${{ github.event.number }}
      environment: dev  # Changed from pr-${{ github.event.number }} to dev
      db_user: app-pr-${{ github.event.number }}
      tags: pr-${{ github.event.pull_request.number }}  # Use tags instead of deprecated tag
      params: >-
        --set global.secrets.persist=false
        --set backend.imagePullPolicy=Always
        --set frontend.imagePullPolicy=Always
        --set backend.deploymentStrategy=Recreate
        --set frontend.deploymentStrategy=Recreate
        --set global.debug=true
        --set backend.resources.requests.memory=256Mi
        --set backend.resources.limits.memory=512Mi
        --set frontend.resources.requests.memory=128Mi
        --set frontend.resources.limits.memory=256Mi
        --set global.namespace.suffix=-pr-${{ github.event.number }}
      triggers: ('backend/' 'frontend/' 'migrations/' 'charts/' '.github/')
      db_triggers: ('charts/crunchy/')
      deployment_url: https://${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}-frontend.apps.silver.devops.gov.bc.ca

  security_scan:
    permissions:
      contents: read
    name: ZAP Security Scan (PR-${{ github.event.number }})
    needs: [deploys]
    uses: ./.github/workflows/.zap-scan.yml
    with:
      target_url: https://${{ github.event.repository.name }}-pr-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca
      fail_on_high: false
      scan_type: baseline

  results:
    name: PR Results
    needs: [builds, deploys, security_scan]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"

  # Comment on PR with deployment URL
  comment:
    name: Comment on PR
    needs: [deploys]
    if: always() && needs.deploys.result == 'success'
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## 🚀 PR Environment Deployed!
            
            **Environment:** `dev`
            **Frontend URL:** https://${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}-frontend.apps.silver.devops.gov.bc.ca
            **Tags:** `pr-${{ github.event.pull_request.number }}`
            
            The application has been deployed to the dev environment with PR-specific resources.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}