name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate PR
    if: ${{ !github.event.pull_request.draft }}
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@v0.9.0
    with:
      markdown_links: |
        - [Frontend](https://${{ github.event.repository.name }}-pr-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca)

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - name: Print success message
        run: echo "✅ Validation job completed!"

      # Optional: Post comment only if PR comes from same repo (not a fork)
      - name: Post PR comment
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.number }} --body "✅ Validation job completed!"

